// Dedicated product illustrations, separate from the masters' portfolios.
export const demoProductCovers = [
  {
    productId: "mika-neon-night",
    imageUrl: "https://picsum.photos/id/208/1200/750",
    sourcePage: "https://unsplash.com/photos/NYxxuBSQzp4",
    credit: "Martin Wessely",
  },
  {
    productId: "mika-rain-cinema",
    imageUrl: "https://picsum.photos/id/211/1200/750",
    sourcePage: "https://unsplash.com/photos/GDvSktiPIQQ",
    credit: "Martin Wessely",
  },
  {
    productId: "mika-soft-film",
    imageUrl: "https://picsum.photos/id/214/1200/750",
    sourcePage: "https://unsplash.com/photos/Ereoqdv5s48",
    credit: "Kelly Sikkema",
  },
  {
    productId: "elena-nordic-matte",
    imageUrl: "https://picsum.photos/id/217/1200/750",
    sourcePage: "https://unsplash.com/photos/YOQDokJipFg",
    credit: "Tom Butler",
  },
  {
    productId: "elena-coastal-air",
    imageUrl: "https://picsum.photos/id/220/1200/750",
    sourcePage: "https://unsplash.com/photos/qUToqliACNA",
    credit: "Robin Röcker",
  },
  {
    productId: "elena-deep-contrast",
    imageUrl: "https://picsum.photos/id/223/1200/750",
    sourcePage: "https://unsplash.com/photos/vwY2D2Wr4ME",
    credit: "Maria Carrasco",
  },
  {
    productId: "yusuf-desert-gold",
    imageUrl: "https://picsum.photos/id/228/1200/750",
    sourcePage: "https://unsplash.com/photos/0AbVUUorULU",
    credit: "Michal Kubicek",
  },
  {
    productId: "yusuf-copper-film",
    imageUrl: "https://picsum.photos/id/231/1200/750",
    sourcePage: "https://unsplash.com/photos/XeCvtUX-AE0",
    credit: "Aleksandra Boguslawska",
  },
  {
    productId: "yusuf-market-warmth",
    imageUrl: "https://picsum.photos/id/234/1200/750",
    sourcePage: "https://unsplash.com/photos/_py5wlZTI2c",
    credit: "Laura Liberal",
  },
  {
    productId: "anna-concrete-minimal",
    imageUrl: "https://picsum.photos/id/237/1200/750",
    sourcePage: "https://unsplash.com/photos/8wTPqxlnKM4",
    credit: "André Spieker",
  },
  {
    productId: "anna-urban-chrome",
    imageUrl: "https://picsum.photos/id/240/1200/750",
    sourcePage: "https://unsplash.com/photos/dFkCXUMB4r4",
    credit: "Elisabetta Foco",
  },
  {
    productId: "anna-studio-neutral",
    imageUrl: "https://picsum.photos/id/243/1200/750",
    sourcePage: "https://unsplash.com/photos/DYW1s0AfLwo",
    credit: "Orlova Maria",
  },
  {
    productId: "lucas-paris-night",
    imageUrl: "https://picsum.photos/id/248/1200/750",
    sourcePage: "https://unsplash.com/photos/tZrrWkQT9MM",
    credit: "Oliver Pacas",
  },
  {
    productId: "lucas-motion-teal",
    imageUrl: "https://picsum.photos/id/251/1200/750",
    sourcePage: "https://unsplash.com/photos/b7g3wVqr1gU",
    credit: "Tiago Gerken",
  },
  {
    productId: "lucas-forest-analog",
    imageUrl: "https://picsum.photos/id/254/1200/750",
    sourcePage: "https://unsplash.com/photos/adG2dX-ruJ4",
    credit: "Pavel Voinov",
  },
  {
    productId: "iryna-kyiv-grain",
    imageUrl: "https://picsum.photos/id/257/1200/750",
    sourcePage: "https://unsplash.com/photos/3EYK2njhLxc",
    credit: "Emanuele Pinna",
  },
  {
    productId: "iryna-storm-story",
    imageUrl: "https://picsum.photos/id/260/1200/750",
    sourcePage: "https://unsplash.com/photos/OdAqbedkfiA",
    credit: "Sylwia Bartyzel",
  },
  {
    productId: "iryna-editorial-skin",
    imageUrl: "https://picsum.photos/id/264/1200/750",
    sourcePage: "https://unsplash.com/photos/XsPM2CBTTpI",
    credit: "Jon Phillips",
  },
  {
    productId: "marcus-clean-portrait",
    imageUrl: "https://picsum.photos/id/267/1200/750",
    sourcePage: "https://unsplash.com/photos/uLLUnacamlo",
    credit: "Robin Benad",
  },
  {
    productId: "marcus-lisbon-blue",
    imageUrl: "https://picsum.photos/id/270/1200/750",
    sourcePage: "https://unsplash.com/photos/TXG9VLN1J9U",
    credit: "Victoria Alexander",
  },
  {
    productId: "marcus-motion-teal",
    imageUrl: "https://picsum.photos/id/273/1200/750",
    sourcePage: "https://unsplash.com/photos/cyi4rNpSxBE",
    credit: "Wim Peters",
  },
  {
    productId: "sofia-vintage-transit",
    imageUrl: "https://picsum.photos/id/276/1200/750",
    sourcePage: "https://unsplash.com/photos/sM3lniBo2LY",
    credit: "davide ragusa",
  },
  {
    productId: "sofia-coastal-air",
    imageUrl: "https://picsum.photos/id/279/1200/750",
    sourcePage: "https://unsplash.com/photos/OHS0yA7OkrQ",
    credit: "Taylor Leopold",
  },
  {
    productId: "sofia-fine-art-light",
    imageUrl: "https://picsum.photos/id/282/1200/750",
    sourcePage: "https://unsplash.com/photos/9dw0xLlxw1s",
    credit: "Taylor Leopold",
  },
  {
    productId: "mika-cyan-orange",
    imageUrl: "https://picsum.photos/id/287/1200/750",
    sourcePage: "https://unsplash.com/photos/c54ZhWDLEDo",
    credit: "Aleksandra Boguslawska",
  },
  {
    productId: "mika-night-contrast",
    imageUrl: "https://picsum.photos/id/290/1200/750",
    sourcePage: "https://unsplash.com/photos/nAZOGbSWK9o",
    credit: "Aleksandar Vacić",
  },
  {
    productId: "elena-clean-cinema",
    imageUrl: "https://picsum.photos/id/293/1200/750",
    sourcePage: "https://unsplash.com/photos/AJqHzUbc1io",
    credit: "Paul E. Harrer",
  },
  {
    productId: "elena-forest-film",
    imageUrl: "https://picsum.photos/id/296/1200/750",
    sourcePage: "https://unsplash.com/photos/Du30R57aCyM",
    credit: "Greg Shield",
  },
  {
    productId: "yusuf-desert-heat",
    imageUrl: "https://picsum.photos/id/300/1200/750",
    sourcePage: "https://unsplash.com/photos/2f_CnEeZsVg",
    credit: "Pavel Voinov",
  },
  {
    productId: "yusuf-skin-tone",
    imageUrl: "https://picsum.photos/id/304/1200/750",
    sourcePage: "https://unsplash.com/photos/_o6AAx9dl_Y",
    credit: "Drew Patrick Miller",
  },
  {
    productId: "anna-clean-cinema",
    imageUrl: "https://picsum.photos/id/307/1200/750",
    sourcePage: "https://unsplash.com/photos/h0Vxgz5tyXA",
    credit: "Keith Misner",
  },
  {
    productId: "anna-night-contrast",
    imageUrl: "https://picsum.photos/id/310/1200/750",
    sourcePage: "https://unsplash.com/photos/YxNW6SqiDD8",
    credit: "Dominik Martin",
  },
  {
    productId: "lucas-cyan-orange",
    imageUrl: "https://picsum.photos/id/313/1200/750",
    sourcePage: "https://unsplash.com/photos/4xYgBTYC2-Q",
    credit: "Sonja Langford",
  },
  {
    productId: "lucas-skin-tone",
    imageUrl: "https://picsum.photos/id/316/1200/750",
    sourcePage: "https://unsplash.com/photos/M8PV59TCj6E",
    credit: "Philipp Reiner",
  },
] as const;
