export const demoDigitalProducts = [
  {
    author: "mika",
    kind: "PRESET",
    id: "mika-neon-night",
    imageUrl: "https://picsum.photos/id/208/1200/750",
    priceMinor: 3900,
    titleKey: "preset.style.neonNight",
    title: "Neon Night",
    look: {
      gain: [0.92, 0.93, 0.91],
      offset: [0, 0, 0],
    },
  },
  {
    author: "mika",
    kind: "PRESET",
    id: "mika-rain-cinema",
    imageUrl: "https://picsum.photos/id/211/1200/750",
    priceMinor: 3200,
    titleKey: "preset.style.rainCinema",
    title: "Rain Cinema",
    look: {
      gain: [0.945, 0.96, 0.93],
      offset: [2, 2, 1],
    },
  },
  {
    author: "mika",
    kind: "PRESET",
    id: "mika-soft-film",
    imageUrl: "https://picsum.photos/id/214/1200/750",
    priceMinor: 2900,
    titleKey: "preset.style.softFilm",
    title: "Soft Film",
    look: {
      gain: [0.97, 0.99, 0.95],
      offset: [4, 4, 2],
    },
  },
  {
    author: "elena",
    kind: "PRESET",
    id: "elena-nordic-matte",
    imageUrl: "https://picsum.photos/id/217/1200/750",
    priceMinor: 3200,
    titleKey: "preset.style.nordicMatte",
    title: "Nordic Matte",
    look: {
      gain: [0.995, 1.02, 0.97],
      offset: [6, 0, 3],
    },
  },
  {
    author: "elena",
    kind: "PRESET",
    id: "elena-coastal-air",
    imageUrl: "https://picsum.photos/id/220/1200/750",
    priceMinor: 2800,
    titleKey: "preset.style.coastalAir",
    title: "Coastal Air",
    look: {
      gain: [1.02, 1.05, 0.99],
      offset: [8, 2, 4],
    },
  },
  {
    author: "elena",
    kind: "PRESET",
    id: "elena-deep-contrast",
    imageUrl: "https://picsum.photos/id/223/1200/750",
    priceMinor: 3600,
    titleKey: "preset.style.deepContrast",
    title: "Deep Contrast",
    look: {
      gain: [1.045, 0.93, 1.01],
      offset: [0, 4, 5],
    },
  },
  {
    author: "yusuf",
    kind: "PRESET",
    id: "yusuf-desert-gold",
    imageUrl: "https://picsum.photos/id/228/1200/750",
    priceMinor: 2700,
    titleKey: "preset.style.desertGold",
    title: "Desert Gold",
    look: {
      gain: [1.07, 0.96, 1.03],
      offset: [2, 0, 6],
    },
  },
  {
    author: "yusuf",
    kind: "PRESET",
    id: "yusuf-copper-film",
    imageUrl: "https://picsum.photos/id/231/1200/750",
    priceMinor: 3100,
    titleKey: "preset.style.copperFilm",
    title: "Copper Film",
    look: {
      gain: [0.92, 0.99, 1.05],
      offset: [4, 2, 0],
    },
  },
  {
    author: "yusuf",
    kind: "PRESET",
    id: "yusuf-market-warmth",
    imageUrl: "https://picsum.photos/id/234/1200/750",
    priceMinor: 2400,
    titleKey: "preset.style.marketWarmth",
    title: "Market Warmth",
    look: {
      gain: [0.945, 1.02, 1.07],
      offset: [6, 4, 1],
    },
  },
  {
    author: "anna",
    kind: "PRESET",
    id: "anna-concrete-minimal",
    imageUrl: "https://picsum.photos/id/237/1200/750",
    priceMinor: 3600,
    titleKey: "preset.style.concreteMinimal",
    title: "Concrete Minimal",
    look: {
      gain: [0.97, 1.05, 0.91],
      offset: [8, 0, 2],
    },
  },
  {
    author: "anna",
    kind: "PRESET",
    id: "anna-urban-chrome",
    imageUrl: "https://picsum.photos/id/240/1200/750",
    priceMinor: 3300,
    titleKey: "preset.style.urbanChrome",
    title: "Urban Chrome",
    look: {
      gain: [0.995, 0.93, 0.93],
      offset: [0, 2, 3],
    },
  },
  {
    author: "anna",
    kind: "PRESET",
    id: "anna-studio-neutral",
    imageUrl: "https://picsum.photos/id/243/1200/750",
    priceMinor: 2900,
    titleKey: "preset.style.studioNeutral",
    title: "Studio Neutral",
    look: {
      gain: [1.02, 0.96, 0.95],
      offset: [2, 4, 4],
    },
  },
  {
    author: "lucas",
    kind: "PRESET",
    id: "lucas-paris-night",
    imageUrl: "https://picsum.photos/id/248/1200/750",
    priceMinor: 4900,
    titleKey: "preset.style.parisNight",
    title: "Paris Night",
    look: {
      gain: [1.045, 0.99, 0.97],
      offset: [4, 0, 5],
    },
  },
  {
    author: "lucas",
    kind: "PRESET",
    id: "lucas-motion-teal",
    imageUrl: "https://picsum.photos/id/251/1200/750",
    priceMinor: 4400,
    titleKey: "preset.style.motionTeal",
    title: "Motion Teal",
    look: {
      gain: [1.07, 1.02, 0.99],
      offset: [6, 2, 6],
    },
  },
  {
    author: "lucas",
    kind: "PRESET",
    id: "lucas-forest-analog",
    imageUrl: "https://picsum.photos/id/254/1200/750",
    priceMinor: 3700,
    titleKey: "preset.style.forestAnalog",
    title: "Forest Analog",
    look: {
      gain: [0.92, 1.05, 1.01],
      offset: [8, 4, 0],
    },
  },
  {
    author: "iryna",
    kind: "PRESET",
    id: "iryna-kyiv-grain",
    imageUrl: "https://picsum.photos/id/257/1200/750",
    priceMinor: 3500,
    titleKey: "preset.style.kyivGrain",
    title: "Kyiv Grain",
    look: {
      gain: [0.945, 0.93, 1.03],
      offset: [0, 0, 1],
    },
  },
  {
    author: "iryna",
    kind: "PRESET",
    id: "iryna-storm-story",
    imageUrl: "https://picsum.photos/id/260/1200/750",
    priceMinor: 3900,
    titleKey: "preset.style.stormStory",
    title: "Storm Story",
    look: {
      gain: [0.97, 0.96, 1.05],
      offset: [2, 2, 2],
    },
  },
  {
    author: "iryna",
    kind: "PRESET",
    id: "iryna-editorial-skin",
    imageUrl: "https://picsum.photos/id/264/1200/750",
    priceMinor: 3200,
    titleKey: "preset.style.editorialSkin",
    title: "Editorial Skin",
    look: {
      gain: [0.995, 0.99, 1.07],
      offset: [4, 4, 3],
    },
  },
  {
    author: "marcus",
    kind: "PRESET",
    id: "marcus-clean-portrait",
    imageUrl: "https://picsum.photos/id/267/1200/750",
    priceMinor: 4200,
    titleKey: "preset.style.cleanPortrait",
    title: "Clean Portrait",
    look: {
      gain: [1.02, 1.02, 0.91],
      offset: [6, 0, 4],
    },
  },
  {
    author: "marcus",
    kind: "PRESET",
    id: "marcus-lisbon-blue",
    imageUrl: "https://picsum.photos/id/270/1200/750",
    priceMinor: 3600,
    titleKey: "preset.style.lisbonBlue",
    title: "Lisbon Blue",
    look: {
      gain: [1.045, 1.05, 0.93],
      offset: [8, 2, 5],
    },
  },
  {
    author: "marcus",
    kind: "PRESET",
    id: "marcus-motion-teal",
    imageUrl: "https://picsum.photos/id/273/1200/750",
    priceMinor: 3900,
    titleKey: "preset.style.motionTeal",
    title: "Motion Teal",
    look: {
      gain: [1.07, 0.93, 0.95],
      offset: [0, 4, 6],
    },
  },
  {
    author: "sofia",
    kind: "PRESET",
    id: "sofia-vintage-transit",
    imageUrl: "https://picsum.photos/id/276/1200/750",
    priceMinor: 4600,
    titleKey: "preset.style.vintageTransit",
    title: "Vintage Transit",
    look: {
      gain: [0.92, 0.96, 0.97],
      offset: [2, 0, 0],
    },
  },
  {
    author: "sofia",
    kind: "PRESET",
    id: "sofia-coastal-air",
    imageUrl: "https://picsum.photos/id/279/1200/750",
    priceMinor: 3800,
    titleKey: "preset.style.coastalAir",
    title: "Coastal Air",
    look: {
      gain: [0.945, 0.99, 0.99],
      offset: [4, 2, 1],
    },
  },
  {
    author: "sofia",
    kind: "PRESET",
    id: "sofia-fine-art-light",
    imageUrl: "https://picsum.photos/id/282/1200/750",
    priceMinor: 4100,
    titleKey: "preset.style.fineArtLight",
    title: "Fine Art Light",
    look: {
      gain: [0.97, 1.02, 1.01],
      offset: [6, 4, 2],
    },
  },
  {
    author: "mika",
    kind: "LUT",
    id: "mika-cyan-orange",
    imageUrl: "https://picsum.photos/id/287/1200/750",
    priceMinor: 3500,
    titleKey: "lut.style.cyanOrange",
    title: "Cyan Orange",
    look: {
      gain: [0.995, 1.05, 1.03],
      offset: [8, 0, 3],
    },
  },
  {
    author: "mika",
    kind: "LUT",
    id: "mika-night-contrast",
    imageUrl: "https://picsum.photos/id/290/1200/750",
    priceMinor: 0,
    titleKey: "lut.style.nightContrast",
    title: "Night Contrast",
    look: {
      gain: [1.02, 0.93, 1.05],
      offset: [0, 2, 4],
    },
  },
  {
    author: "elena",
    kind: "LUT",
    id: "elena-clean-cinema",
    imageUrl: "https://picsum.photos/id/293/1200/750",
    priceMinor: 3100,
    titleKey: "lut.style.cleanCinema",
    title: "Clean Cinema",
    look: {
      gain: [1.045, 0.96, 1.07],
      offset: [2, 4, 5],
    },
  },
  {
    author: "elena",
    kind: "LUT",
    id: "elena-forest-film",
    imageUrl: "https://picsum.photos/id/296/1200/750",
    priceMinor: 2600,
    titleKey: "lut.style.forestFilm",
    title: "Forest Film",
    look: {
      gain: [1.07, 0.99, 0.91],
      offset: [4, 0, 6],
    },
  },
  {
    author: "yusuf",
    kind: "LUT",
    id: "yusuf-desert-heat",
    imageUrl: "https://picsum.photos/id/300/1200/750",
    priceMinor: 2400,
    titleKey: "lut.style.desertHeat",
    title: "Desert Heat",
    look: {
      gain: [0.92, 1.02, 0.93],
      offset: [6, 2, 0],
    },
  },
  {
    author: "yusuf",
    kind: "LUT",
    id: "yusuf-skin-tone",
    imageUrl: "https://picsum.photos/id/304/1200/750",
    priceMinor: 0,
    titleKey: "lut.style.skinTone",
    title: "Skin Tone",
    look: {
      gain: [0.945, 1.05, 0.95],
      offset: [8, 4, 1],
    },
  },
  {
    author: "anna",
    kind: "LUT",
    id: "anna-clean-cinema",
    imageUrl: "https://picsum.photos/id/307/1200/750",
    priceMinor: 3300,
    titleKey: "lut.style.cleanCinema",
    title: "Clean Cinema",
    look: {
      gain: [0.97, 0.93, 0.97],
      offset: [0, 0, 2],
    },
  },
  {
    author: "anna",
    kind: "LUT",
    id: "anna-night-contrast",
    imageUrl: "https://picsum.photos/id/310/1200/750",
    priceMinor: 2800,
    titleKey: "lut.style.nightContrast",
    title: "Night Contrast",
    look: {
      gain: [0.995, 0.96, 0.99],
      offset: [2, 2, 3],
    },
  },
  {
    author: "lucas",
    kind: "LUT",
    id: "lucas-cyan-orange",
    imageUrl: "https://picsum.photos/id/313/1200/750",
    priceMinor: 4600,
    titleKey: "lut.style.cyanOrange",
    title: "Cyan Orange",
    look: {
      gain: [1.02, 0.99, 1.01],
      offset: [4, 4, 4],
    },
  },
  {
    author: "lucas",
    kind: "LUT",
    id: "lucas-skin-tone",
    imageUrl: "https://picsum.photos/id/316/1200/750",
    priceMinor: 3900,
    titleKey: "lut.style.skinTone",
    title: "Skin Tone",
    look: {
      gain: [1.045, 1.02, 1.03],
      offset: [6, 0, 5],
    },
  },
] as const;
